-- AlterTable
ALTER TABLE "Article" ALTER COLUMN "redirect" SET DEFAULT '';

-- CreateTable
CREATE TABLE "Applicant" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "fullName" TEXT,
    "mobile" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "propertyType" TEXT NOT NULL,
    "dealType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "budgetMin" BIGINT,
    "budgetMax" BIGINT,
    "province" TEXT,
    "city" TEXT,
    "district" TEXT,
    "address" TEXT,
    "postalCode" TEXT,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "viewCount" INTEGER NOT NULL DEFAULT 0,
    "minLandArea" BIGINT,
    "maxLandArea" BIGINT,
    "minBuildingArea" BIGINT,
    "maxBuildingArea" BIGINT,
    "minRoomNumber" INTEGER,
    "maxRoomNumber" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "buildingFacade" TEXT[],
    "floorCovering" TEXT[],
    "commonAreas" TEXT[],
    "heatingCooling" TEXT[],
    "kitchenFeatures" TEXT[],
    "otherFeatures" TEXT[],
    "parkingTypes" TEXT[],
    "propertySpecs" TEXT[],
    "utilities" TEXT[],
    "wallCeiling" TEXT[],
    "categoryTitle" TEXT,
    "propertydirection" TEXT,
    "propertyUnit" TEXT,
    "propertyFloors" TEXT,
    "floor" TEXT,
    "unitInFloor" TEXT,
    "allUnit" TEXT,
    "seoTitle" TEXT,
    "seoMeta" TEXT,
    "seoCanonikalOrigin" TEXT,
    "seoCanonikalDestination" TEXT,
    "seoOrigin" TEXT,
    "seoDestination" TEXT,
    "seoRedirect" TEXT,

    CONSTRAINT "Applicant_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Applicant_slug_key" ON "Applicant"("slug");
