-- AlterTable
ALTER TABLE "Article" ALTER COLUMN "redirect" SET DEFAULT '',
ALTER COLUMN "seoCanonikalDestination" DROP DEFAULT,
ALTER COLUMN "seoCanonikalOrigin" DROP DEFAULT,
ALTER COLUMN "seoDestination" DROP DEFAULT,
ALTER COLUMN "seoMeta" DROP DEFAULT,
ALTER COLUMN "seoOrigin" DROP DEFAULT,
ALTER COLUMN "seoRedirect" DROP DEFAULT,
ALTER COLUMN "seoTitle" DROP DEFAULT;
